export const SULFURAS_DEFAULT_QUALITY = 80;
export const MAX_STANDARD_QUALITY = 50;
export const MIN_STANDARD_QUALITY = 0;

export const STANDARD_DEFAULT_QUALITY_UPDATE = 1;
export const FAST_DEFAULT_QUALITY_UPDATE = 2;

export const CONJURED_DEFAULT_QUALITY_UPDATE = 2;
export const CONJURED_FAST_DEGRADATION_RATE = 4;

export const BACKSTAGE_SLOW_QUALITY_DAY_MINIMUM = 10;
export const BACKSTAGE_MEDIUM_QUALITY_DAY_MINIMUM = 5;
export const BACKSTAGE_TIER_1_QUALITY = 1;
export const BACKSTAGE_TIER_2_QUALITY = 2;
export const BACKSTAGE_TIER_3_QUALITY = 3;
